require('dotenv').config();

module.exports = {
  MONGODB_URI: process.env.MONGODB_URI,
  PARSE_ADMIN_PASSWORD: process.env.PARSE_ADMIN_DASHBOARD_PASSWORD,
  PARSE_ADMIN_USERNAME: process.env.PARSE_ADMIN_DASHBOARD_USERNAME,
  PARSE_APP_ID: process.env.PARSE_APP_ID,
  PARSE_CLIENT_KEY: process.env.PARSE_CLIENT_KEY,
  PARSE_DASHBOARD_APP_NAME: process.env.PARSE_DASHBOARD_APP_NAME,
  PARSE_MASTER_KEY: process.env.PARSE_MASTER_KEY,
  PARSE_SERVER_MOUNT: process.env.PARSE_SERVER_MOUNT,
  PARSE_SERVER_URL: process.env.PARSE_SERVER_URL,
  PORTAL_URL: process.env.PORTAL_URL,
  SENDGRID_API_KEY: process.env.SENDGRID_API_KEY,
  SENDGRID_FROM_EMAIL: process.env.SENDGRID_FROM_EMAIL,
  STRIPE_API_KEY: process.env.STRIPE_API_KEY,
  S3_SECRET_KEY: process.env.S3_SECRET_KEY,
  S3_ACCESS_KEY: process.env.S3_ACCESS_KEY,
  S3_BUCKET: process.env.S3_BUCKET,
};
